### ISSUE TITLE
git@github.com:the-teacher/rails7-docker.git does not exist

### ISSUE THREAD

**Issue by odysseyjason** [the-teacher/rails7-startkit#1]
The rails7-startkit instructions ask for git clone git@github.com:the-teacher/rails7-docker.git, but git says 'Please make sure you have the correct access rights and the repository exists.' for git clone git@github.com:the-teacher/rails7-docker.git as per the instructions.

**Comment by the-teacher** [comment]
Hello! Thank you for your help!

I have it updated

```sh
git clone https://github.com/the-teacher/rails7-startkit.git
cd rails7-startkit
bin/setup
```

Can you please check the new instructions?
