### ISSUE TITLE
rails-start.com redirects to cooking site

### ISSUE THREAD

**Issue by rhulse** [the-teacher/rails7-startkit#37]
In a nutshell, the one liner appears to be broken.

**Comment by the-teacher** [comment]
@rhulse Hi sir! Sorry. It is my old cook blog for my wife. I've done a mistake in NGINX configurations. Not a problem I hope =)

I have removed this short option to setup the project. It was not the best idea to use it, but I wanted to try.
Now I have some reasons to avoid supporting solutions like that.
