### ISSUE TITLE
Windows. Testing

### ISSUE THREAD

**Issue by Kronen10** [the-teacher/rails7-startkit#40]
![photo_5454308900997287116_y](https://github.com/the-teacher/rails7-startkit/assets/99847305/0a3d9628-1eb0-44b2-b308-aed5f1dbf600)
![photo_5454308900997287115_y](https://github.com/the-teacher/rails7-startkit/assets/99847305/c4cf9b7c-1dae-4484-bb0b-c53e0f02cf62)
![photo_5454308900997287129_y](https://github.com/the-teacher/rails7-startkit/assets/99847305/a1f68dee-5315-4e2a-974b-9bf9cdccc32a)
![photo_5454308900997287124_y](https://github.com/the-teacher/rails7-startkit/assets/99847305/c069cc9d-9e52-4669-b5cd-c350573a8c4d)
![photo_5454308900997287123_y](https://github.com/the-teacher/rails7-startkit/assets/99847305/5aa436e0-5d21-4900-9dfa-1c1e6ff8b952)
![photo_5454308900997287119_x](https://github.com/the-teacher/rails7-startkit/assets/99847305/78a19211-fb3e-41be-aeab-eabfe27ea161)
![photo_5454308900997287117_x](https://github.com/the-teacher/rails7-startkit/assets/99847305/0b0e8fe1-185a-47ee-bef3-fdf0c107e9ba)

**Comment by the-teacher** [comment]
<img width="1355" alt="Screenshot 2023-09-08 at 22 20 15" src="https://github.com/the-teacher/rails7-startkit/assets/496713/277f6d4f-295c-4fb6-a081-fa091d4857f6">
<img width="813" alt="Screenshot 2023-09-08 at 22 20 26" src="https://github.com/the-teacher/rails7-startkit/assets/496713/a6fed4ee-9845-4e55-ad24-7e8edd7e9d48">
<img width="810" alt="Screenshot 2023-09-08 at 22 20 38" src="https://github.com/the-teacher/rails7-startkit/assets/496713/a996dab9-23e0-478e-b5c9-5997a7406715">

**Comment by the-teacher** [comment]
<img width="555" alt="Screenshot 2023-09-08 at 22 19 29" src="https://github.com/the-teacher/rails7-startkit/assets/496713/f8d40041-4b93-4e23-acbb-9171f2c9c335">
<img width="1184" alt="Screenshot 2023-09-08 at 22 19 14" src="https://github.com/the-teacher/rails7-startkit/assets/496713/93ef7967-24b4-4420-a995-026646d33d17">
