### ISSUE TITLE
service "rails" is not running container #1

### ISSUE THREAD

**Issue by gkeepa** [the-teacher/rails7-startkit#9]
hi, when runing bin/setup, kept getting the following error after step #3

$bin/setup
Docker version 20.10.23, build 7155243
1. Launching PgSQL container
[+] Running 1/0
 ⠿ Container rails7app-psql-1  Running                                                                                                                                                                0.0s
Waiting 3 seconds to initialize PgSQL database
touch db/PGSQL/.keep
2. Launching ElasticSearch Container
[+] Running 1/1
 ⠿ Container rails7app-elastic-1  Started                                                                                                                                                             0.5s
Waiting 10 seconds to launch ElasticSearch Container
3. Launching Rails container
[+] Running 2/2
 ⠿ Container rails7app-psql-1   Running                                                                                                                                                               0.0s
 ⠿ Container rails7app-rails-1  Started                                                                                                                                                               0.6s
Waiting 3 seconds to launch Rails Container
4. Installing Gems. Please Wait
Install Gems
docker compose -f docker/docker-compose.yml exec  rails /bin/bash -c 'bundle install'
service "rails" is not running container #1

**Comment by the-teacher** [comment]
Please do the same, and after it is failed do `$ bin/status`

It should be like that

```
$ bin/setup
```

```
Launching PgSQL container
[+] Running 1/0
⠿ Container rails7app-psql-1 Running 0.0s
Waiting 3 seconds to initialize PgSQL database
touch db/PGSQL/.keep
Launching ElasticSearch Container
[+] Running 1/1
⠿ Container rails7app-elastic-1 Started 0.5s
Waiting 10 seconds to launch ElasticSearch Container
Launching Rails container
[+] Running 2/2
⠿ Container rails7app-psql-1 Running 0.0s
⠿ Container rails7app-rails-1 Started 0.6s
Waiting 3 seconds to launch Rails Container
Installing Gems. Please Wait
Install Gems
docker compose -f docker/docker-compose.yml exec rails /bin/bash -c 'bundle install'
service "rails" is not running container
```

```
$ bin/status
```

also you can try to see what the following command does for you:

```
$ docker compose -f docker/docker-compose.yml exec rails /bin/bash
```

**Comment by gkeepa** [comment]
t$ bin/status

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
NAMES               IMAGE                    PORTS      CONTAINER ID
rails7app-redis-1   redis:7.0.5-alpine       6379/tcp   ae1940cb9cb0
rails7app-psql-1    postgres:15.1-bullseye   5432/tcp   1a6ef780a05c
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
docker compose -f docker/docker-compose.yml exec  rails /bin/bash -c 'ps a | grep puma'
service "rails" is not running container #1
docker compose -f docker/docker-compose.yml exec  rails /bin/bash -c 'ps a | grep sidekiq'
service "rails" is not running container #1


$ docker compose -f docker/docker-compose.yml exec rails /bin/bash
service "rails" is not running container #1

**Comment by gkeepa** [comment]
addition info:

$ docker container ls -a
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS                     PORTS      NAMES
ae1940cb9cb0   redis:7.0.5-alpine             "docker-entrypoint.s…"   21 hours ago    Up 21 hours                6379/tcp   rails7app-redis-1
bcaa69e081b6   iamteacher/rails7:2023.arm64   "irb"                    21 hours ago    Exited (1) 21 hours ago               rails7app-rails-1
aae1fdc98ed1   elasticsearch:7.17.8           "/bin/tini -- /usr/l…"   21 hours ago    Exited (1) 21 hours ago               rails7app-elastic-1
1a6ef780a05c   postgres:15.1-bullseye         "docker-entrypoint.s…"   22 hours ago    Up 22 hours                5432/tcp   rails7app-psql-1


$ docker container run rails7app-rails-1
Unable to find image 'rails7app-rails-1:latest' locally
docker: Error response from daemon: pull access denied for rails7app-rails-1, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by the-teacher** [comment]
@gkeepa I do not understand why rails container didn't start for you

Can you please try run rails container manually?

From the root of the project:

```sh
docker compose -f docker/docker-compose.yml up rails
```

**Comment by the-teacher** [comment]
I can accept that `rails` container, which was done by me was broken. But there is also `elastic` which also didn't start. It looks weird.

**Comment by gkeepa** [comment]
$ docker compose -f docker/docker-compose.yml up rails
[+] Running 2/0
 ⠿ Container rails7app-psql-1   Running                                                                                                                                                               0.0s
 ⠿ Container rails7app-rails-1  Created                                                                                                                                                               0.0s
Attaching to rails7app-rails-1
rails7app-rails-1  | exec /usr/local/bin/irb: exec format error
rails7app-rails-1 exited with code 1


$ docker compose -f docker/docker-compose.yml up elastic
[+] Running 1/0
 ⠿ Container rails7app-elastic-1  Created                                                                                                                                                             0.0s
Attaching to rails7app-elastic-1
rails7app-elastic-1  | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
rails7app-elastic-1  | output:
rails7app-elastic-1  | [0.000s][error][logging] Error opening log file 'logs/gc.log': Permission denied
rails7app-elastic-1  | [0.000s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
rails7app-elastic-1  | error:
rails7app-elastic-1  | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
rails7app-elastic-1  | Error: Could not create the Java Virtual Machine.
rails7app-elastic-1  | Error: A fatal exception has occurred. Program will exit.
rails7app-elastic-1  | 	at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:119)
rails7app-elastic-1  | 	at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)
rails7app-elastic-1  | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)
rails7app-elastic-1  | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)
rails7app-elastic-1  | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
rails7app-elastic-1 exited with code 1

**Comment by the-teacher** [comment]
Hey @gkeepa ! Hello again. Thank you for you patience and that you still trying to solve the case.
Unfortunately I should say that I do not know a solution and I'm not able to reproduce it on my laptop. So I do not know how to help.

Based on you message I found the following issue. Maybe it will give you some ideas about what happens on your side.
https://github.com/elastic/elasticsearch/issues/64872

**Comment by gkeepa** [comment]
ok, the elasticsearch container is up.  the reason for the error was ../log/ELASTIC was owned by root, that's why it couldnt create the gc.log file.

and the rail issue was due to the platform was arm64, my laptop was amd64

so now all the container is running now, however, i still can't access http://localhost:3000

bin/status

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
NAMES                 IMAGE                          PORTS                                       CONTAINER ID
rails7app-rails-1     iamteacher/rails7:2023.amd64   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   84d26f5558c6
rails7app-redis-1     redis:7.0.5-alpine             6379/tcp                                    ae1940cb9cb0
rails7app-elastic-1   elasticsearch:7.17.8           9200/tcp, 9300/tcp                          aae1fdc98ed1
rails7app-psql-1      postgres:15.1-bullseye         5432/tcp                                    1a6ef780a05c
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
docker compose -f docker/docker-compose.yml exec  rails /bin/bash -c 'ps a | grep puma'
    267 pts/1    Ss+    0:00 /bin/bash -c ps a | grep puma
    275 pts/1    S+     0:00 grep puma
docker compose -f docker/docker-compose.yml exec  rails /bin/bash -c 'ps a | grep sidekiq'
    276 pts/1    Ss+    0:00 /bin/bash -c ps a | grep sidekiq
    284 pts/1    S+     0:00 grep sidekiq

**Comment by gkeepa** [comment]
nevermind, more permission issue, tmp also need to be given permission, it's all working now, i can see the site up at localhost:3000
